### ISSUE TITLE
Tag 2.0.1 still a snapshot

### ISSUE THREAD

**Issue by eitch** [petitparser/java-petitparser#10]
Hello Lukas

Your created the tag 2.0.1, but your version in the pom is still 2.0.1-SNAPSHOT, thus i can't use the following as a dependency:

    <dependency>
	    <groupId>com.github.petitparser.java-petitparser</groupId>
	    <artifactId>petitparser</artifactId>
	    <version>2.0.1</version>
	</dependency>

Could you please create a version where the POM version and the JitPack Version coincide?

**Comment by renggli** [comment]
Sorry, I missed that because I am not using Maven myself. Please let me know if this works with 644c8f34272c383d590eeccb9a77530489efaabd and `<version>2.0.2</version>`.

**Comment by eitch** [comment]
Yes, now it works. Thanks.
