### ISSUE TITLE
petitparser on maven central

### ISSUE THREAD

**Issue by McFoggy** [petitparser/java-petitparser#15]
I know that #5 has been closed because of jitpack deployment but I would really like that you reconsider to publish the library on maven central.

Like you I provide some OSS libraries ; one of them is [jgitver](https://jgitver.github.io/) which consist of 3 projects:
- a library jar using java-petitparser; built with maven
- a maven plugin as a core maven extension; built with maven
- a gradle plugin; built with gradle

The problem of jitpack, is as being a non standard repository, end users of plugins/libs have to declare in their build tool the usage of jitpack even if they just use 'plugins' and not directly your library.

This means for jgitver plugins that jitpack has to be present not just in the standard dependencies scope but also in the plugin dependencies scope:
- thus a specific `pluginRepositories` setting for maven
- a specific `buildscript>repositories ` setting for gradle

Having java-petitparser in central would just be transparent for any one using it anywhere in anytool.

Like many others I personally publish to central via sonatype. If you follow the instructions there (https://central.sonatype.org/pages/ossrh-guide.html) it is a no brainer.

Without a deployment to central, I see only 2 possibilities for me:
1. refactor to remove the usage of java-petitparser
2. fork, relocate under fr.brouillard.oss, and publish to central so that it is available out of the box as a resolvable dependency in maven & gradle.

I am going to do 2. right now otherwise I cannot publish my latest version of the gradle plugin but I would really prefer to avoid any of the 2 mentioned possibilities.

Thanks for your understanding.

**Comment by McFoggy** [comment]
FYI I forked here https://github.com/jgitver/java-petitparser/tree/jgitver and just pushed

```
<groupId>fr.brouillard.oss.com.github.petitparser</groupId>
<artifactId>petitparser-core</artifactId>
<version>2.1.0-jgitver</version>
```

It will find its way to central in the following minutes/hours once the synchronization between sonatype & central occur.

**Comment by renggli** [comment]
Thank you, I'll give it another try to publish to Maven Central and let you know how it goes. Your [changes](https://github.com/jgitver/java-petitparser/tree/jgitver) and the links to working documentation will certainly help. Hopefully, things are simpler in the meantime :-)

**Comment by McFoggy** [comment]
Perfect thank you for your reconsideration.

**Comment by renggli** [comment]
Managed to run `mvn -Poss -DskipTests deploy`.

**Comment by McFoggy** [comment]
I see it on Sonatype repo https://oss.sonatype.org/content/groups/public/com/github/petitparser/petitparser-core/2.2.0/

It should be on its way to central.

**Comment by renggli** [comment]
Is there anything else I can / should do?

**Comment by McFoggy** [comment]
no perfect, your lib is on central

![image](https://user-images.githubusercontent.com/1119660/48092798-f81e7d00-e20d-11e8-846d-8dae98f9b9be.png)

**Comment by renggli** [comment]
Thank you for your help and your pushing on getting it there 👍
