### ISSUE TITLE
Question : Is petitparser able to support function ?

### ISSUE THREAD

**Issue by ebocher** [petitparser/java-petitparser#16]
I would like to develop a basic expression parser with the following syntax 

bbox('0,0,0,0') and key = 'building' or tag='surface'

The expression chain must support a reserved list of keywords (key, tag) but should be extensible by functions as bbox is.

Then, I need to extract the expression tree to perform actions. 

Thanks in advance for you advice.

**Comment by renggli** [comment]
It is not clear to me what exactly you are trying to do, but that should definitely be possible. Have a look at the the [numerous examples](https://github.com/petitparser/dart-petitparser/tree/master/example) or the (mostly basic examples) in the [tests](https://github.com/petitparser/dart-petitparser/blob/master/petitparser/test/petitparser_test.dart).

**Comment by renggli** [comment]
Making as obsolete.
