### ISSUE TITLE
Parser error when combining existing parser

### ISSUE THREAD

**Issue by RaveenSasidharan** [petitparser/java-petitparser#17]
I have wrote parser for if else block like below.
-----------------Parser Code------------------------
        ifBlock.set(ifOperator.seq(conditionParser)
                .map((List<Boolean> values)-> String.valueOf(values.get(1))));

        elseBlock.set(elseOperator.seq(of('('),
                                                numParser
                                                .or(extractBlock)
                                                ,of(')'))
                                                .map((List<String> values) -> values.get(2)));

        //.or(ifElseParser)

        thenBlock.set(thenOperator.seq(of('('),
                                                numParser
                                                .or(extractBlock)
                                                ,of(')'))
                                                .map((List<String> values) -> values.get(2)));

        ifElseParser.set(ifBlock
                            .seq( thenBlock,elseBlock).or(thenBlock)

when i tried ifBlock, elseBlock, thenBlock seperately, the parser is working fine. And when I combined these three into ifElseParser, it is showing error
 
------------------------Code for Log------------------

Log.e("Test", "ifBlock"+ifBlock.parse("IF(EQUALS(1,1))"));
        Log.e("Test", "elseBlock"+elseBlock.parse("ELSE(EXTRACT(FALSE))"));
        Log.e("Test", "thenBlock"+thenBlock.parse("THEN(EXTRACT(TRUE))"));
        Log.e("Test", "ifElseParser"+ifElseParser.parse("IF(EQUALS(1,1))THEN(EXTRACT(TRUE))ELSE(EXTRACT(FALSE))"));

 
------------------- Log Output-----------------
E/Test: ifBlockSuccess[1:16]: true
E/Test: elseBlockSuccess[1:21]: FALSE
E/Test: thenBlockSuccess[1:20]: TRUE
E/Test: ifElseParserFailure[1:3]: E

**Comment by renggli** [comment]
Could you provide a [minimal-reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by RaveenSasidharan** [comment]
The issue was not with the parser
