### ISSUE TITLE
Can you release a new version with ExpressionBuilder Wrapper?

### ISSUE THREAD

**Issue by philipparndt** [petitparser/java-petitparser#18]
Hi @renggli,

Thanks for the great library!

Can you please release a new version for Java? The wrapper feature for the `ExpressionBuilder` is really nice 👍 The [using the expression builder](https://github.com/petitparser/dart-petitparser#using-the-expression-builder) section in the Dart repo is also great, maybe you can adapt this for Java. There are only some small changes to do, I've implemented this as test case [here](https://github.com/philipparndt/java-petitparser/blob/master/petitparser-core/src/test/java/org/petitparser/ExpressionBuilderCalculatorExampleTest.java).

**Comment by renggli** [comment]
Hi @philipparndt,

Thank you for the kind comments. I've released 2.3.0 with the latest code. Feel free to submit a pull request with your test case and updated documentation.
