### ISSUE TITLE
Target Java 11 (LTS)

### ISSUE THREAD

**Issue by krka** [petitparser/java-petitparser#20]
First of all, thanks for making this - so far it seems like a very convenient way to write grammars/parsers!

I am currently using Java 11, which is the LTS version.
So now I have to either upgrade to Java 12 or downgrade this library to 2.2.0, but then I would lose ExpressionGroup.wrapper().

Hopefully it would not be too much work to set the release target to 11 instead of 12. It might be as simple as adding

    <configuration>
        <release>11</release>
    </configuration>

to the pom file.

**Comment by renggli** [comment]
Thank you. Released 2.3.1 with release target 11.

**Comment by krka** [comment]
Thanks for the quick response!

**Comment by kdbeall** [comment]
@renggli Hi, would it be possible to target Java 8 by default? I have compiled and tested with no failures on Java 8. On the OpenJDK Java 8 will be supported until May 2026.
