### ISSUE TITLE
Trim problems

### ISSUE THREAD

**Issue by philipparndt** [petitparser/java-petitparser#22]
Hi @renggli 

while looking on a issue with a parser that is written with java-petitparser I figured out the following problem:

When `flatten().trim()` is executed multiple times (in that case this was caused by some shared parts between different parsers, this behaves unexpected. Example:

```
Parser parser = of('a').flatten().trim().flatten().trim();
assertSuccess(parser, " a ", "a"); // expected "a" but is "a "
```

Another example:
```
Parser parser = new SequenceParser(
        of('a').flatten().trim(),
        of('b').flatten().trim(),
        of('c').flatten().trim())
        .flatten().trim();

assertSuccess(parser, " a b c ", "abc"); // expected "abc" but is "a b c "
```

The root cause is that the `FlattenParser` uses the result position of the `TrimmingParser` and the space to the right seems to be already handled.
I have a suggested solution for this issue and will create a PR.

**Comment by renggli** [comment]
Thank you for the bug report and the pull request. The behavior you are observing is definitely surprising, but I am not yet convinced that adding more logic actually solves the problem? Having nested flattening operations is definitely a strange thing to have in a parser. Maybe it is worth to rather refactor the grammar, or if it is auto-generated remove it programmatically? I'll have a more in-depth look later tonight ...

**Comment by philipparndt** [comment]
Thanks for having a look at it. I see your point. First I implemented a completely different fix but wasn't happy either. That introduced a new result type for the `TrimmingParser` with an additional position that can be handled within the `FlattenParser`.

**Comment by renggli** [comment]
I think the pull request changes the described behavior of the `FlattenParser`: _Returns a parser that discards the result of the receiver, and returns a sub-string of the consumed range in the string/list being parsed._ Particularly the _discards_ part is no longer true, instead the `FlattenParser` suddenly depends on what the receiver consumes. Furthermore the change makes it impossible to switch to the fast-parse mode.

As far as I see, you could do the joining in a custom parser, or even a production action?

**Comment by philipparndt** [comment]
Thanks for the feedback I've closed the PR. As a workaround it is possible to remove the flatten or trimming parts from the parser. But it took some time to figure out whats going wrong. Due to this I'd liked to improve this. When it's only me having this issue, we can close it as unfortunately we still stick at Java 8 for the project we use this anyway :(
