### ISSUE TITLE
README.md refers to non-existing tutorial

### ISSUE THREAD

**Issue by renggli** [petitparser/java-petitparser#3]
The file README.md refers to non-existing tutorial.

**Comment by hastebrot** [comment]
Link in `README.md` to the introductory tutorial in class documentation is 404'ed again.

http://www.lukas-renggli.ch/job/java-petitparser/javadoc/index.html?org/petitparser/package-summary.html

**Comment by renggli** [comment]
As of 1cee97ba0022a2f95a53fc48d936d0fbfdceb8a9 integrated the tutorial with README.md to avoid the problem in the future.

**Comment by hastebrot** [comment]
Amazing. Thanks!
