### ISSUE TITLE
module support

### ISSUE THREAD

**Issue by johampel** [petitparser/java-petitparser#47]
Currently, neither a module-info.java nor an according entry in the META-INF/MANIFEST.MF exists. The result is, if you use this library in a Module based JavaProject, you have to import petitparser as a filename-based automodule into the project, which ends up (for maven) with a warning like:

`[WARNING] ********************************************************************************************************************
[WARNING] * Required filename-based automodules detected. Please don't publish this project to a public artifact repository! *
[WARNING] ********************************************************************************************************************
[`

So it would be nice, if this project would have a stable module name, either provided via a module-info.java file or an `Automatic-Module-Name` entry in the manifest file

**Comment by renggli** [comment]
Could you provide a pull request? I am not familiar how Java modules work ...

**Comment by johampel** [comment]
I can try, but after digging a little bit, I saw that you already provided a module-info.java which looks ok. The problem I described is gone as soon as i add the Automatic-Module-Name to the manifest, but honestly I am not sure why this is the case, since I thought that the presence of the module-info.java is sufficient. Have to analyse first

**Comment by johampel** [comment]
Ok, got it: My problem would be fixed in case you decide to build a new release with the software as it is, since with commit 0b818e29ff you already added a module-info.java (14 month ago), but you didn't created a new version since 6. Jan 2020, if I got it right.

Is it possible for you to create a new release?

**Comment by renggli** [comment]
I've updated `4.2.0` on Maven Central. Please note that this is the last update of the package on Maven Central: https://github.com/petitparser/java-petitparser?tab=readme-ov-file#maven-central-deprecated
