### ISSUE TITLE
Maven: Missing artifact on Maven Central

### ISSUE THREAD

**Issue by hastebrot** [petitparser/java-petitparser#5]
Hey!

Gradle could not download the artifact. GitHub says version 2.0.0 was released in April, but the artifacts seems missing: https://search.maven.org/#search|ga|1|petitparser

Snippet from my `build.gradle`:

~~~groovy
repositories {
    mavenCentral()
}

dependencies {
    compile "org.codehaus.groovy:groovy-all:2.4.3"
    compile "com.github.petitparser:petitparser-core:2.0.0"

    testCompile "junit:junit:4.12"
}

~~~

**Comment by hastebrot** [comment]
Ahh, I think I have to deploy the artifacts to my local `.m2`.

**Comment by renggli** [comment]
Yeah, sorry about that. I didn't manage to get it on Maven Central. This seems to be incredibly hard. Any instructions, tutorials, help, ... that are up-to-date and that work out of the box would be appreciated.

**Comment by hastebrot** [comment]
True. It took me hours to manage uploads.

The easy part is to create a JIRA account at Sonatype and a new project ticket [1] for `com.github.petitparser`. You later need your username and password to `deploy` your artifacts to Maven Central.

The harder part is to ensure all required metadata is in the `pom.xml`, sign the artifacts with cryptographic keys, and upload the artifacts to the staging area.

My workflow is to upload my artifacts via Gradle and the Bintray plugin to Bintray, pass them to Bintray's JCenter, let Bintray sign the artifacts with their cryptographic keys and let them upload the artifacts to Sonatype's Maven Central.

I don't know if Gradle would be fine for you, it seems that your Maven solution already nice and easy. I'll see if I could find some information on how to add the Bintray plugin to Maven `pom.xml`s, if this simplifies the workflow.

[1] http://central.sonatype.org/pages/ossrh-guide.html#create-a-ticket-with-sonatype

**Comment by hastebrot** [comment]
Seems to be pretty easy. Here a some examples for Maven: https://github.com/bintray/bintray-examples/tree/master/maven-example

Also here is a clean tutorial: http://veithen.github.io/2013/05/26/github-bintray-maven-release-plugin.html

The nice thing about Bintray is, that one can upload the artifacts to any place they own (for testing purposes), and later remove the uploaded artifacts.

**Comment by renggli** [comment]
I tried similar tutorials with Sonatype and Bintray back in November; and now with the tutorial you suggested to absolutely no avail.

**Comment by renggli** [comment]
Finally found an easy and automatic way to create a Maven artifacts: https://jitpack.io/#petitparser/java-petitparser

Added a version batch with 07ab323c159e445653a88c3f5d099d2f9cac58c5.
Updated installation instructions with 10f0130fb9e332ec7040af56b81e2d1a53e62a46.

**Comment by aesy** [comment]
Hey Lukas, I can guide you through the process of getting it on maven central if you'd like?

**Comment by renggli** [comment]
Thank you for your offer, Isak. I think the current solution with JitPack works pretty well and needs little to no attention when a new release is made. If you think a Maven Central artefact would still be useful, feel free to create one.
