### ISSUE TITLE
Improved messages (support for autocompletion)

### ISSUE THREAD

**Issue by bpieber** [petitparser/java-petitparser#50]
Hi Lukas,

Given the following Parser:
`Parser parser = StringParser.of("ABC").or(StringParser.of("DEF"));`

When I parse the empty string:
`String message = parser.parse("").getMessage();`

I get the following message:
`DEF expected`

I wonder how difficult it would be to somehow get the following instead/in addition to?
`ABC OR DEF expected`

That would be also be helpful to implement autocompletion based on the grammar. (Xtext can do this IIRC.)

Cheers,
Bernhard

**Comment by renggli** [comment]
This is something that has been added in the Dart version of PetitParser a while ago (https://github.com/petitparser/dart-petitparser/issues/98 and https://github.com/petitparser/dart-petitparser/commit/a9225cb47769812e607f35cd3dd2e70dcd790bea), but was never ported to the Java version.

Backport is almost ready.

**Comment by bpieber** [comment]
Wow! Thanks for the insanely fast backport!

**Comment by LMnet** [comment]
Hi @renggli ! I found that whereas this issue is marked as resolved and the fix is in master, there is no maven release with the fix. Could you please make a release with this functionality?
