### ISSUE TITLE
JitPack build for main failed

### ISSUE THREAD

**Issue by bpieber** [petitparser/java-petitparser#51]
I would like to use the latest code in the main branch in a Maven project. I tried to get it from https://jitpack.io/#petitparser/java-petitparser using the following in pom.xlm

```
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.github.petitparser</groupId>
            <artifactId>java-petitparser</artifactId>
            <version>main-SNAPSHOT</version>
        </dependency>
    </dependencies>
```

However, I get the following error:
`[ERROR] Failed to execute goal on project learning-petitparser: Could not resolve dependencies for project com.modelligent:learning-petitparser:jar:1.0.0-SNAPSHOT: Could not find artifact com.github.petitparser:java-petitparser:jar:main-1f87c1e664-1 in jitpack.io (https://jitpack.io) -> [Help 1]`

It looks like the last build ran into a failure:
https://jitpack.io/com/github/petitparser/java-petitparser/main-1f87c1e664-1/build.log

Cheers,
Bernhard

**Comment by bpieber** [comment]
I cloned petitparser/java-petitparser and ran `mvn clean install` locally. As I expected I got a `BUILD SUCCESS` result. I use Apache Maven 3.8.1 bundled with IntelliJ. JitPack used 3.6.1 for its build.

Here is the error message from the build.log:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project petitparser-core: Fatal error compiling: invalid flag: --release -> [Help 1]`

FWIW, googling brought up this:
https://stackoverflow.com/questions/49105941/intellij-maven-project-fatal-error-compiling-invalid-flag-release

Reading this, maybe JitPack needs to be told somehow to use Java 11? It used Java 8 for the build. However, as you may have noted, I am somewhat out of my depth here.

Cheers,
Bernhard

**Comment by bpieber** [comment]
Maybe it is a general JitPack problem?
https://github.com/jitpack/jitpack.io/issues/5301

Cheers,
Bernhard

**Comment by renggli** [comment]
I've increased the JavaSDK version to 8 and then 17, but now there is a different error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.7.0:jar (attach-javadocs) on project petitparser: The plugin org.apache.maven.plugins:maven-javadoc-plugin:3.7.0 requires Maven version 3.6.3 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginIncompatibleException
```

**Comment by vintaerj** [comment]
No updates about this issue ?

**Comment by renggli** [comment]
I am not familiar with Maven or JitPack, happy to merge a pull request if somebody has an idea how to fix the issue?

**Comment by ScottiSws** [comment]
Sorry for the duplicate issue. I hope I can make it up to you with a pull request for your main branch that fixes it. I added Maven Wrapper so you can now choose the version of Maven to build with.

https://github.com/petitparser/java-petitparser/pull/77

**Comment by renggli** [comment]
It looks like the wrapper fixes this. Thank you!

**Comment by ScottiSws** [comment]
You're very welcome.
