### ISSUE TITLE
Question: How to consume max inputs as possible ?

### ISSUE THREAD

**Issue by vintaerj** [petitparser/java-petitparser#79]
Hello,

How to consume max inputs on a given parser ?

For example:

```java
final Parser parser = StringParser.ofIgnoringCase("al").or(StringParser.ofIgnoringCase("all")).
parser.parse("all");
````

The first parser caught the input `al`, but it is not intended (in my business logic). I would like that the second parser catch the input `all`.

Thank you for your response !

**Comment by renggli** [comment]
The or-parser is an ordered choice. This means it always picks the first matching choice. 

This means you have to re-order the choice in order of preference. In your case you can write the parser as `StringParser.ofIgnoringCase("all").or(StringParser.ofIgnoringCase("al"))`.

**Comment by vintaerj** [comment]
Thanks for your answer. I thought there might be another solution, but this should be enough.

**Comment by renggli** [comment]
There are certainly other solutions, for example people have been implementing their own `LongestChoiceParser` that tries all the variants and picks the longest one succeeding. While this would work in your simple case, in more general cases (and particularly in recursive cases) this can lead to exponentially growing parse-times and other difficult to understand parser bugs ...
