### ISSUE TITLE
How to get meaningfull getMessage() of a parse result if parsing fails in optional parser?

### ISSUE THREAD

**Issue by meier-rene** [petitparser/java-petitparser#80]
Hi, this is more a question than an issue. I can not find out how to get a nice failure message in case of an parse failure in an optional parser. Instead I get the message that the following non optional parser fails. 
Example:
A string to parse:
```
line1 value
line2 !
line3 value
```
My parser definition:
```
def("start",
ref("line1")
.seq(ref("line2").optional)
.seq(ref("line3"))
.end()

def("line1", StringParser.of("line1 ") 
.seq(CharacterParser.word().plusLazy(Token.NEWLINE_PARSER)
 .seq(Token.NEWLINE_PARSER));

def("line2", StringParser.of("line2 ") 
.seq(CharacterParser.word().plusLazy(Token.NEWLINE_PARSER)
 .seq(Token.NEWLINE_PARSER));

def("line3", StringParser.of("line3 ") 
.seq(CharacterParser.word().plusLazy(Token.NEWLINE_PARSER)
 .seq(Token.NEWLINE_PARSER));
```
If I parse the string I get `line3 expected` at the beginning of line 2 from getMessages(). This is in principle correct, but it would be more usefull if I would get something like `letter or digit expected` at the end of the line 2.

Can someone give me an advice how to get better Messages in case of failure of an optional parser?

**Comment by renggli** [comment]
You can get the desired behavior by reordering the choices. That is you try first `line1` followed by `line3`; and only then `line1` followed by `line2` followed by `line3`:

```java
def("start", ref("line1")
    .seq(ref("line3")
        .or(ref("line2").seq(ref("line3"))))
    .end());
```

**Comment by meier-rene** [comment]
Thank you for your suggestions. Unfortunately this will get a bit too complicated, because I have multiple lines with optional components and if I understand it correctly I would have to put all possible combinations in the parser definition. Never mind, I will augment the messages from the parser with some additional logging to make the identification of the actual syntax problem a bit easier.  

I would like to thank you for this very nice library. It makes parsing of complicated data really easy.
