### ISSUE TITLE
Please deploy simple petitparser-core

### ISSUE THREAD

**Issue by eitch** [petitparser/java-petitparser#9]
I don't need all the additional JARs and would be happier if i could only pull in core.

I tried with: 

	<dependency>
		<groupId>com.github.petitparser</groupId>
		<artifactId>petitparser-core</artifactId>
		<version>2.0.0</version>
	</dependency>

but this is not deployed.

**Comment by renggli** [comment]
This should work, but I couldn't try yet:

        <dependency>
            <groupId>com.github.petitparser.java-petitparser</groupId>
            <artifactId>petitparser-core</artifactId>
            <version>2.0.0</version>
        </dependency>

See here for an example: https://github.com/jitpack/maven-modular

**Comment by renggli** [comment]
Added this instruction to README.md in 418c742715b951e82610ad391f7d4d80058e03d5.
